version: '3'
services:
  frontend:
    build:
      dockerfile: Dockerfile
      context: ./frontend
    container_name: app_frontend
    volumes:
      - /app/node_modules
      - ./frontend:/app
    stdin_open: true

  nginx:
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - 80:80

  backend:
    build:
      dockerfile: Dockerfile
      context: ./backend
    container_name: app_backend
    volumes:
      - ./backend:/app
